url: "https://runwithsai.com/"
baseurl: ""
title: "Run with Sai"
description: "Join Run with Sai for marathons and charity events across Cambodia."
keywords: "marathon, charity, running, angkor wat, sports events, cambodia"
author: "Run with Sai Team"

# Open Graph and Twitter Image Defaults
# Customizable per-page or event
og_image: "assets/images/about_us.jpg"
twitter_image: "assets/images/about_us.jpg"

# SEO Tags - You can set unique images or titles for each page/event by specifying them in front matter
# Example for a specific page or event:
# og_image: "/assets/images/specific_event_image.jpg"
# twitter_image: "/assets/images/specific_event_image.jpg"

# Plugins to be used
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Allow future posts to be published
future: true

# Collections
collections:
  events:
    output: true
    permalink: /events/:slug/
  supporters:
    output: true

# Prose Settings (content management and metadata)
prose:
  media: "media"
  ignore:
    - _includes
    - _layouts
    - .github
    - .vscode
    - assets
    - _config.yml
    - .gitignore
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - script.js
    - style.css
  metadata:
    _supporters:
      - name: "logo_path"
        field:
          element: "text"
          label: "Logo"
          value: ""
      - name: "alt"
        field:
          element: "text"
          label: "Alternative text"
          value: ""
    _events:
      - name: "event_title"
        field:
          element: "text"
          label: "Event Title"
          value: ""
      - name: "section"
        field:
          element: "select"
          label: "Section"
          options:
            - name: "Sport Events"
            - name: "Charity Projects"
      - name: "date"
        field:
          element: "text"
          label: "Event Date (YYYY-MM-DD)"
          value: ""
        # Ensure the format follows YYYY-MM-DD, for example: 2025-03-23
        # You can validate it via Prose UI to ensure it stays consistent.
      - name: "images"
        field:
          element: "text"
          label: "Event Images (comma-separated URLs)"
          value: ""
        # Allow users to add multiple event image URLs, separated by commas
        # For example: "assets/images/event1.jpg,assets/images/event2.jpg"
